Collections:
  - Name: Mask2Former
    Metadata:
      Training Data: COCO
      Training Techniques:
        - AdamW
        - Weight Decay
      Training Resources: 8x A100 GPUs
      Architecture:
        - Mask2Former
    Paper:
      URL: https://arxiv.org/pdf/2112.01527
      Title: 'Masked-attention Mask Transformer for Universal Image Segmentation'
    README: configs/mask2former/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.23.0/mmdet/models/detectors/mask2former.py#L7
      Version: v2.23.0

Models:
- Name: mask2former_r50_lsj_8x2_50e_coco
  In Collection: Mask2Former
  Config: configs/mask2former/mask2former_r50_lsj_8x2_50e_coco.py
  Metadata:
    Training Memory (GB): 13.9
    Iterations: 368750
  Results:
  - Task: Object Detection
    Dataset: COCO
    Metrics:
      box AP: 44.8
  - Task: Instance Segmentation
    Dataset: COCO
    Metrics:
      mask AP: 41.9
  - Task: Panoptic Segmentation
    Dataset: COCO
    Metrics:
      PQ: 51.9
  Weights: https://download.openmmlab.com/mmdetection/v2.0/mask2former/mask2former_r50_lsj_8x2_50e_coco/mask2former_r50_lsj_8x2_50e_coco_20220326_224516-0091ce2b.pth
- Name: mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco
  In Collection: Mask2Former
  Config: configs/mask2former/mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco.py
  Metadata:
    Training Memory (GB): 15.9
    Iterations: 368750
  Results:
  - Task: Object Detection
    Dataset: COCO
    Metrics:
      box AP: 46.3
  - Task: Instance Segmentation
    Dataset: COCO
    Metrics:
      mask AP: 43.4
  - Task: Panoptic Segmentation
    Dataset: COCO
    Metrics:
      PQ: 53.4
  Weights: https://download.openmmlab.com/mmdetection/v2.0/mask2former/mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco/mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco_20220326_224553-c92f921c.pth
